#!/bin/bash
# Certificate Generator - Multi-Agent Launch Helper

echo "🚀 Certificate Generator - Multi-Agent Launch Instructions"
echo "========================================================"
echo ""
echo "This project uses 5 specialized agents working in parallel."
echo "Each agent needs to be launched in a separate terminal."
echo ""
echo "STEP 1: Create worktrees (run once)"
echo "------------------------------------"
echo "cd /home/marsh/coding/Safesteps"
echo "git worktree add ../cert-gen-infra main"
echo "git worktree add ../cert-gen-auth main"
echo "git worktree add ../cert-gen-pdf main"
echo "git worktree add ../cert-gen-storage main"
echo "git worktree add ../cert-gen-docs main"
echo ""
echo "STEP 2: Launch each agent in a new terminal"
echo "-------------------------------------------"
echo ""
echo "Terminal 1 - Infrastructure Agent:"
echo "cd ../cert-gen-infra"
echo "# Copy and paste the prompt from:"
echo "# /home/marsh/coding/Safesteps/.claude/commands/infrastructure_agent_prompt.md"
echo ""
echo "Terminal 2 - Auth & Admin Agent:"
echo "cd ../cert-gen-auth"
echo "# Copy and paste the prompt from:"
echo "# /home/marsh/coding/Safesteps/.claude/commands/auth_admin_agent_prompt.md"
echo ""
echo "Terminal 3 - PDF Generation Agent:"
echo "cd ../cert-gen-pdf"
echo "# Copy and paste the prompt from:"
echo "# /home/marsh/coding/Safesteps/.claude/commands/pdf_generation_agent_prompt.md"
echo ""
echo "Terminal 4 - Storage & Integration Agent:"
echo "cd ../cert-gen-storage"
echo "# Copy and paste the prompt from:"
echo "# /home/marsh/coding/Safesteps/.claude/commands/storage_integration_agent_prompt.md"
echo ""
echo "Terminal 5 - Documentation & Testing Agent:"
echo "cd ../cert-gen-docs"
echo "# Copy and paste the prompt from:"
echo "# /home/marsh/coding/Safesteps/.claude/commands/documentation_testing_agent_prompt.md"
echo ""
echo "STEP 3: Monitor progress"
echo "------------------------"
echo "watch -n 5 'cat /tmp/claude-team/progress.md'"
echo ""
echo "STEP 4: Check for issues"
echo "------------------------"
echo "tail -f /tmp/claude-team/issues.md"
echo ""
echo "📝 Note: Agents will update their progress every 5 minutes"
echo "🔄 They communicate via /tmp/claude-team/ files"
echo "⚡ Launch Infrastructure Agent first, others can start immediately after"